#pragma once
#include <string>

#include "I18nKeys.h"

// THIS FILE IS AUTO-GENERATED BY gen_i18n.py. DO NOT EDIT.

namespace i18n_strings {

extern const char* const STRINGS_EN[];
extern const char* const STRINGS_ES[];
extern const char* const STRINGS_FR[];
extern const char* const STRINGS_DE[];
extern const char* const STRINGS_CZ[];
extern const char* const STRINGS_PO[];
extern const char* const STRINGS_RU[];
extern const char* const STRINGS_SV[];

}  // namespace i18n_strings
